// ISO 3166-1 alpha-3 country code to country name mapping
export const codeToCountry: Map<string, string[]> = new Map<string, string[]>([
  ["AFG", ["Afghanistan"]],
  ["ALB", ["Albania"]],
  ["DZA", ["Algeria"]],
  ["AND", []],
  ["AGO", ["Angola"]],
  ["ARG", ["Argentina"]],
  ["ARM", ["Armenia"]],
  ["ATA", ["Antarctica"]],
  ["AUS", ["Australia"]],
  ["AUT", ["Austria"]],
  ["AZE", ["Azerbaijan"]],
  ["BDI", ["Burundi"]],
  ["BEL", ["Belgium"]],
  ["BEN", ["Benin"]],
  ["BFA", ["Burkina Faso"]],
  ["BGD", ["Bangladesh"]],
  ["BGR", ["Bulgaria"]],
  ["BHS", ["Bahamas"]],
  ["BIH", ["Bosnia and Herz."]],
  ["BLR", ["Belarus"]],
  ["BLZ", ["Belize"]],
  ["BOL", ["Bolivia"]],
  ["BRA", ["Brazil"]],
  ["BRN", ["Brunei"]],
  ["BTN", ["Bhutan"]],
  ["BWA", ["Botswana"]],
  ["CAF", ["Central African Rep."]],
  ["CAN", ["Canada"]],
  ["CHE", ["Switzerland"]],
  ["CHL", ["Chile"]],
  ["CHN", ["China"]],
  ["CIV", ["Côte d'Ivoire"]],
  ["CMR", ["Cameroon"]],
  ["COD", ["Dem. Rep. Congo"]],
  ["COG", ["Congo"]],
  ["COL", ["Colombia"]],
  ["CRI", ["Costa Rica"]],
  ["CUB", ["Cuba"]],
  ["CYP", ["Cyprus", "N. Cyprus"]],
  ["CZE", ["Czechia"]],
  ["DEU", ["Germany"]],
  ["DNK", ["Denmark"]],
  ["DJI", ["Djibouti"]],
  ["DOM", ["Dominican Rep."]],
  ["ECU", ["Ecuador"]],
  ["EGY", ["Egypt"]],
  ["ERI", ["Eritrea"]],
  ["ESP", ["Spain"]],
  ["EST", ["Estonia"]],
  ["ETH", ["Ethiopia"]],
  ["FIN", ["Finland"]],
  ["FJI", ["Fiji"]],
  ["FLK", ["Falkland Is."]],
  ["FRA", ["France"]],
  ["GAB", ["Gabon"]],
  ["GBR", ["United Kingdom"]],
  ["GEO", ["Georgia"]],
  ["GHA", ["Ghana"]],
  ["GIN", ["Guinea"]],
  ["GMB", ["Gambia"]],
  ["GNB", ["Guinea-Bissau"]],
  ["GNQ", ["Eq. Guinea"]],
  ["GRC", ["Greece"]],
  ["GRL", ["Greenland"]],
  ["GTM", ["Guatemala"]],
  ["GUY", ["Guyana"]],
  ["HND", ["Honduras"]],
  ["HTI", ["Haiti"]],
  ["HUN", ["Hungary"]],
  ["IDN", ["Indonesia"]],
  ["IND", ["India"]],
  ["IRN", ["Iran"]],
  ["IRQ", ["Iraq"]],
  ["ISL", ["Iceland"]],
  ["ISR", ["Israel"]],
  ["ITA", ["Italy"]],
  ["JAM", ["Jamaica"]],
  ["JOR", ["Jordan"]],
  ["JPN", ["Japan"]],
  ["KAZ", ["Kazakhstan"]],
  ["KEN", ["Kenya"]],
  ["KGZ", ["Kyrgyzstan"]],
  ["KHM", ["Cambodia"]],
  ["KOR", ["South Korea"]],
  ["KWT", ["Kuwait"]],
  ["LAO", ["Laos"]],
  ["LBN", ["Lebanon"]],
  ["LBR", ["Liberia"]],
  ["LKA", ["Sri Lanka"]],
  ["LSO", ["Lesotho"]],
  ["LTU", ["Lithuania"]],
  ["LUX", ["Luxembourg"]],
  ["LVA", ["Latvia"]],
  ["MAR", ["Morocco"]],
  ["MDA", ["Moldova"]],
  ["MDG", ["Madagascar"]],
  ["MEX", ["Mexico"]],
  ["MKD", ["Macedonia"]],
  ["MLI", ["Mali"]],
  ["MMR", ["Myanmar"]],
  ["MNE", ["Montenegro"]],
  ["MNG", ["Mongolia"]],
  ["MOZ", ["Mozambique"]],
  ["MRT", ["Mauritania"]],
  ["MWI", ["Malawi"]],
  ["MYS", ["Malaysia"]],
  ["NAM", ["Namibia"]],
  ["NCL", ["New Caledonia"]],
  ["NER", ["Niger"]],
  ["NGA", ["Nigeria"]],
  ["NIC", ["Nicaragua"]],
  ["NLD", ["Netherlands"]],
  ["NOR", ["Norway"]],
  ["NPL", ["Nepal"]],
  ["NZL", ["New Zealand"]],
  ["OMN", ["Oman"]],
  ["PAK", ["Pakistan"]],
  ["PAN", ["Panama"]],
  ["PER", ["Peru"]],
  ["PHL", ["Philippines"]],
  ["PNG", ["Papua New Guinea"]],
  ["POL", ["Poland"]],
  ["PRK", ["North Korea"]],
  ["PRT", ["Portugal"]],
  ["PRY", ["Paraguay"]],
  ["QAT", ["Qatar"]],
  ["ROU", ["Romania"]],
  ["RUS", ["Russia"]],
  ["RWA", ["Rwanda"]],
  ["SAU", ["Saudi Arabia"]],
  ["SDN", ["Sudan"]],
  ["SEN", ["Senegal"]],
  ["SLB", ["Solomon Is."]],
  ["SLE", ["Sierra Leone"]],
  ["SLV", ["El Salvador"]],
  ["SRB", ["Serbia"]],
  ["SSD", ["S. Sudan"]],
  ["SVK", ["Slovakia"]],
  ["SVN", ["Slovenia"]],
  ["SWE", ["Sweden"]],
  ["SWZ", ["eSwatini"]],
  ["SYR", ["Syria"]],
  ["TCD", ["Chad"]],
  ["TGO", ["Togo"]],
  ["THA", ["Thailand"]],
  ["TJK", ["Tajikistan"]],
  ["TKM", ["Turkmenistan"]],
  ["TLS", ["Timor-Leste"]],
  ["TTO", ["Trinidad and Tobago"]],
  ["TUN", ["Tunisia"]],
  ["TUR", ["Turkey"]],
  ["TWN", ["Taiwan"]],
  ["TZA", ["Tanzania"]],
  ["UGA", ["Uganda"]],
  ["UKR", ["Ukraine"]],
  ["URY", ["Uruguay"]],
  ["USA", ["United States of America"]],
  ["UZB", ["Uzbekistan"]],
  ["VEN", ["Venezuela"]],
  ["VNM", ["Vietnam"]],
  ["VUT", ["Vanuatu"]],
  ["YEM", ["Yemen"]],
  ["ZAF", ["South Africa"]],
  ["ZMB", ["Zambia"]],
  ["ZWE", ["Zimbabwe"]],
  ["ARE", ["United Arab Emirates"]],
  ["ATF", ["Fr. S. Antarctic Lands"]],
  ["ESH", ["W. Sahara"]],
  ["IRL", ["Ireland"]],
  ["PRI", ["Puerto Rico"]],
  ["PSE", ["Palestine"]],
  ["SOM", ["Somalia", "Somaliland"]],
  ["KOS", ["Kosovo"]],
  ["HRV", ["Croatia"]],
  ["SGP", ["Singapore"]],
])

// Simple ISO code to country name mapping (for overlay/sidepanel)
export const isoToCountryName: Record<string, string> = {
  'JPN': 'Japan', 'THA': 'Thailand', 'ITA': 'Italy', 'FRA': 'France', 
  'ESP': 'Spain', 'GRC': 'Greece', 'PRT': 'Portugal', 'USA': 'United States',
  'MEX': 'Mexico', 'BRA': 'Brazil', 'ARG': 'Argentina', 'CHL': 'Chile',
  'PER': 'Peru', 'COL': 'Colombia', 'CAN': 'Canada', 'GBR': 'United Kingdom',
  'IRL': 'Ireland', 'DEU': 'Germany', 'AUT': 'Austria', 'CHE': 'Switzerland',
  'NLD': 'Netherlands', 'BEL': 'Belgium', 'DNK': 'Denmark', 'SWE': 'Sweden',
  'NOR': 'Norway', 'FIN': 'Finland', 'ISL': 'Iceland', 'POL': 'Poland',
  'CZE': 'Czech Republic', 'HUN': 'Hungary', 'ROU': 'Romania', 'BGR': 'Bulgaria',
  'HRV': 'Croatia', 'SVN': 'Slovenia', 'TUR': 'Turkey', 'EGY': 'Egypt',
  'MAR': 'Morocco', 'ZAF': 'South Africa', 'KEN': 'Kenya', 'TZA': 'Tanzania',
  'AUS': 'Australia', 'NZL': 'New Zealand', 'CHN': 'China', 'KOR': 'South Korea',
  'VNM': 'Vietnam', 'IDN': 'Indonesia', 'MYS': 'Malaysia', 'SGP': 'Singapore',
  'PHL': 'Philippines', 'IND': 'India', 'NPL': 'Nepal', 'LKA': 'Sri Lanka',
  'ARE': 'United Arab Emirates', 'QAT': 'Qatar', 'ISR': 'Israel', 'JOR': 'Jordan'
}

// Helper to get country name from ISO code
export function getCountryName(countryCode: string): string {
  // If it's a 3-letter code, it's likely an ISO code
  if (countryCode.length === 3 && countryCode === countryCode.toUpperCase()) {
    return isoToCountryName[countryCode] || countryCode
  }
  return countryCode
}

